version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app
  app:
    build: .
    environment:
      DSN: "postgresql://app:1234@db:5432/app"
    ports:
      - "5000:5000"
    depends_on:
      - db










